const projects = [
  {id:'att',name:'Attention & respiration',category:'quotidien',label:'Le quotidien',art:'<div class="breathing-art"></div>',summary:'Des sons d’ambiance et un guide visuel pour une séance d’attention et de respiration.',need:'Créer une interface simple pour piloter des sons et suivre un rythme de respiration.',evidence:'Interface web et gestion audio présentes dans le code. Portage Android décrit dans la documentation.',demo:'Sélectionner des sons, démarrer la lecture et suivre le guide de respiration.',limit:'Le parcours audio et le portage mobile doivent être vérifiés. La présentation ne formule aucune promesse thérapeutique.'},
  {id:'frise',name:'Frise chronologique',category:'donnees',label:'Les données',art:'<div class="frise-art"><span></span><i></i><span></span><i></i><span></span><i></i><span></span></div>',summary:'Passer d’un tableau de dates à une chronologie que l’on peut parcourir et filtrer.',need:'Rendre une série d’événements compréhensible dans une interface interactive.',evidence:'Composants Vue et services d’import Google Sheets, Framacalc et CSV présents.',demo:'Importer un jeu de dates fictives, rechercher un événement et parcourir la frise.',limit:'Les imports et les différentes représentations doivent être testés avant ouverture d’une démo publique.'},
  {id:'recits',name:'Un tableau pour les récits',category:'creation',label:'La création',art:'<div class="recits-art"><span>Personnage</span><span>Une scène</span><span>Une idée</span></div>',summary:'Organiser des personnages, relier des idées et donner une place aux scènes d’une histoire.',need:'Disposer d’un espace visuel pour préparer un récit et explorer ses relations.',evidence:'Code de cartes, notes, liens, scènes et sauvegarde présent dans l’application.',demo:'Déplacer des cartes, ajouter une note et construire un petit récit.',limit:'Deux dossiers locaux se recoupent. La version de référence et le parcours de sauvegarde restent à valider.'},
  {id:'mains',name:'Studio mains',category:'creation',label:'La création',art:'<span class="art-icon">✋</span>',summary:'Explorer une autre interface : des gestes devant la webcam deviennent des commandes musicales.',need:'Jouer avec une interface musicale sans clavier ni souris.',evidence:'Pages de prototypes utilisant MediaPipe Hands et Tone.js présentes.',demo:'Reconnaître une main et déclencher des interactions musicales.',limit:'La caméra, le son et le chargement des bibliothèques nécessitent un essai sur les navigateurs ciblés.'},
  {id:'portfolio',name:'Un portfolio d’artiste',category:'creation',label:'La création',art:'<div class="recits-art"><span>Portrait</span><span>Parcours<br>Photos · Vidéos</span></div>',summary:'Rassembler une biographie, des photos et des vidéos dans un site vitrine pour le casting.',need:'Présenter le parcours de Fred2Baro aux professionnels du cinéma et du théâtre.',evidence:'Pages de biographie, galeries, contact et script d’interface présents.',demo:'Parcourir le site, puis expliquer la transformation des contenus en pages.',limit:'Les droits sur les médias et les traces de fabrication doivent être documentés avant leur réutilisation ici.'},
  {id:'tada',name:'Garder le fil de ses projets',category:'automatisation',label:'L’automatisation',art:'<div class="recits-art"><span>En cours</span><span>Prochaine action</span></div>',summary:'Un tableau de bord Git pour suivre l’activité et préparer de petites actions concrètes.',need:'Centraliser des projets GitHub et GitLab pour retrouver une prochaine action.',evidence:'Frontend Vue, backend Python et service IA présents dans le dépôt.',demo:'Explorer des projets fictifs et un exemple de bilan.',limit:'La démo doit utiliser des données fictives. Les intégrations Git et IA restent à vérifier.'},
  {id:'finances',name:'Voir ses données autrement',category:'donnees',label:'Les données',art:'<div class="bars"><i></i><i></i><i></i><i></i></div>',summary:'Des graphiques et des vues de trésorerie pour rendre les chiffres plus lisibles.',need:'Transformer des données financières en représentations compréhensibles.',evidence:'Pages de prévision, de suivi des dépenses et tests d’import présents.',demo:'Explorer une série financière inventée, sans aucune donnée personnelle.',limit:'Une version de démonstration séparée reste à préparer. Aucun chiffre privé n’est publié ici.'},
  {id:'woodat',name:'Woodat — comprendre qui est cité',category:'automatisation',label:'L’automatisation',art:'<div class="recits-art"><span>Article</span><span>Personnes<br>Sources</span></div>',summary:'Une extension Firefox qui relie la lecture d’un article à des chronologies biographiques sourcées.',need:'Passer des personnes citées dans un article à des éléments de contexte.',evidence:'Code d’extension et de serveur présents. Recherche et export documentés.',demo:'Montrer le parcours article, personnes, chronologie et sources.',limit:'Les réponses IA doivent être relues. La démo requiert un accès API et une gestion des coûts.'},
];
projects.push({id:'roundnet',name:'Roundnet Worlds 2026',category:'quotidien',label:'Le quotidien',art:'<span class="art-icon">◉</span>',summary:'Un guide non officiel pour retrouver le programme, les accès et les informations du mondial de roundnet.',need:'Rassembler les informations utiles aux visiteurs du mondial de roundnet 2026 à Champigny-sur-Marne.',evidence:'Site public avec programme, accès et transports, informations pratiques, équipes et versions multilingues.',demo:'Parcourir le programme, préparer son trajet et consulter les informations sur les équipes.',limit:'Guide non officiel consacré à un événement passé, du 2 au 6 septembre 2026. Les informations historiques ne constituent pas un programme à venir.'});
projects.push({id:'amina',name:'Les bijoux d’Amina',category:'creation',label:'La création',summary:'Une boutique visuelle pour découvrir des bijoux et personnaliser une gravure avec un aperçu immédiat.',need:'Présenter une collection de bijoux et explorer la personnalisation d’un produit.',evidence:'Site publié sur Cloudflare Pages. Interface de fiche produit, aperçu de gravure et panier présents dans le code.',demo:'Parcourir la boutique, choisir une gravure et voir son rendu sur le produit.',limit:'Le panier est une simulation. Aucun paiement réel n’est proposé dans cette démonstration.'});
projects.push({id:'cloudflamme',name:'CloudFlamme',category:'donnees',label:'Les données',art:'<div class="mobile-previews"><img src="images/cloudflamme-analytics.png" alt="" loading="lazy"><img src="images/cloudflamme-comptes.png" alt="" loading="lazy"></div>',summary:'Suivre plusieurs comptes Cloudflare depuis une application mobile : domaines, DNS et courbes de trafic.',need:'Retrouver ses sites et suivre leur activité dans une interface mobile.',evidence:'Application Android testée avec quatre profils, lecture des DNS, réglages SSL et sécurité, événements et statistiques horaires.',demo:'Voir les comptes enregistrés, choisir un site et consulter sa courbe de requêtes sur les dernières 24 heures.',limit:'Les captures montrent l’application Android. Son utilisation nécessite un jeton Cloudflare personnel ; aucune version web publique n’est proposée.'});
const sites={amina:'https://les-bijous-damina-chezmehdi-net.pages.dev/',att:'https://att.chezmehdi.net/',recits:'https://recits.chezmehdi.net/',portfolio:'https://fred2baro.chezmehdi.net/',woodat:'https://charte-de-munich.org/',roundnet:'https://roundnet.placedelinfo.org/'};
for(const p of projects){p.url=sites[p.id];p.hasPreview=['att','recits','portfolio','roundnet','mains','amina'].includes(p.id);}
const grid=document.querySelector('#project-grid');
const dialog=document.querySelector('#project-dialog');
for(const p of projects){const card=document.createElement('article');card.className='project-card';card.dataset.category=p.category;card.innerHTML=`<div class="art art-${p.id}" aria-hidden="true">${p.hasPreview?`<img src="images/${p.id}.png" alt="Aperçu du site ${p.name}" loading="lazy" width="1360" height="900">`:p.art}</div><div class="card-body"><span class="card-category">${p.label}</span><h3>${p.name}</h3><p>${p.summary}</p><div class="card-actions"><button data-project="${p.id}">Découvrir le projet <span aria-hidden="true">↗</span><span class="sr-only"> : ${p.name}</span></button>${p.url?`<a class="visit-link" href="${p.url}" target="_blank" rel="noopener noreferrer">${p.id==='woodat'?'Découvrir l’extension':'Voir le site'} <span aria-hidden="true">↗</span><span class="sr-only"> : ${p.name} (nouvel onglet)</span></a>`:''}</div></div>`;grid.append(card);}
for(const button of document.querySelectorAll('[data-filter]'))button.addEventListener('click',()=>{for(const b of document.querySelectorAll('[data-filter]'))b.setAttribute('aria-pressed',String(b===button));let count=0;for(const card of grid.children){card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter;if(!card.hidden)count++;}document.querySelector('#result-count').textContent=`${count} projets affichés`;});
grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;const p=projects.find(p=>p.id===button.dataset.project);document.querySelector('#dialog-content').innerHTML=`<span class="status-label">${p.id==='cloudflamme' ? 'Application Android · captures réelles' : p.url ? (p.id==='woodat' ? 'Extension Firefox · présentation sur Charte de Munich' : 'Site accessible · parcours à explorer') : 'Projet existant · démonstration à préparer'}</span><h2>${p.name}</h2>${p.id==='mains'?'<img class="project-preview" src="images/mains.png" alt="Studio mains : détection de deux mains avec repères gestuels">':''}${p.id==='cloudflamme'?'<div class="mobile-gallery"><figure><img src="images/cloudflamme-analytics.png" alt="CloudFlamme : sélection de placedelaloi.fr et courbe des requêtes par heure"><figcaption>Suivre le trafic d’un site</figcaption></figure><figure><img src="images/cloudflamme-comptes.png" alt="CloudFlamme : quatre comptes enregistrés et domaines du compte sélectionné"><figcaption>Passer d’un compte à l’autre</figcaption></figure></div>':''}${p.url?`<a class="button primary" href="${p.url}" target="_blank" rel="noopener noreferrer">${p.id==='woodat'?'Découvrir Woodat':'Ouvrir le site'} ↗<span class="sr-only"> (nouvel onglet)</span></a>`:''}<h3>Le besoin</h3><p>${p.need}</p><h3>Ce qui existe</h3><p>${p.evidence}</p><h3>Ce que l’on peut montrer</h3><p>${p.demo}</p><h3>Ce qui reste à vérifier</h3><p>${p.limit}</p><p>Les prompts, les contributions humaines et les tests seront ajoutés lorsqu’ils seront documentés.</p>`;dialog.showModal();});
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const title=document.querySelector('#demo-title');title.addEventListener('input',()=>{document.querySelector('#live-title').textContent=title.value.trim()||'Votre prochaine idée';});
const colors={bleu:'#2548db',violet:'#7044c1',vert:'#18735e'};
for(const input of document.querySelectorAll('[name=theme]'))input.addEventListener('change',()=>document.querySelector('#live-demo').style.setProperty('--accent',colors[input.value]));
function updateProgress(){const count=document.querySelectorAll('#idea-list input:checked').length;document.querySelector('#demo-progress').textContent=`${count} étape${count>1?'s':''} sur 3 terminée${count>1?'s':''}`;}
document.querySelector('#idea-list').addEventListener('change',updateProgress);
document.querySelector('#reset-demo').addEventListener('click',()=>{title.value='Mes prochaines idées';title.dispatchEvent(new Event('input'));document.querySelector('[name=theme][value=bleu]').checked=true;document.querySelector('#live-demo').style.removeProperty('--accent');for(const box of document.querySelectorAll('#idea-list input'))box.checked=false;updateProgress();});
